language: python
python:
  - "3.6.4"
#blacklisting
branches:
  except:
    - master
    - gh-pages
#white listing
branches:
   only:
     - challenge_2


install:
  - pip install -r requirements.txt
  - pip install nose

# command to run tests
script:
  - pytest

after_success:
  - coveralls